CREATE TABLE IF NOT EXISTS `airport`(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `code` VARCHAR(20) NOT NULL UNIQUE,
    `name` VARCHAR(300) NOT NULL,
    `category` VARCHAR(100) NOT NULL,
    `location` VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS `flight` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `flight_id` VARCHAR(100) NOT NULL UNIQUE,
    `origin_airport` VARCHAR(20) NOT NULL REFERENCES `airport`(`code`),
    `destination_airport` VARCHAR(20) NOT NULL REFERENCES `airport`(`code`),
    `departure_date` DATETIME NOT NULL,
    `arrival_date` DATETIME NOT NULL,
    `price` FLOAT NOT NULL,
    `remaining_seat` SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS `booking`(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `booking_id` VARCHAR(100) NOT NULL UNIQUE,
    `flight_id` VARCHAR(100) NOT NULL REFERENCES `flight`(`flight_id`)
);

CREATE TABLE IF NOT EXISTS `passenger` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(300) NOT NULL,
    `identification` VARCHAR(300) NOT NULL,
    `booking_id` VARCHAR(100) NOT NULL REFERENCES `booking`(`booking_id`)
);

-- INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES (
-- AIRPORT --
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Iskandar Muda","BTJ","Internasional","Banda Aceh");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Cut Nyak Dhien","MEQ","Domestik","Nagan Raya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Lasikin","SNB","Domestik","Sinabang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Maimun Saleh","SBG","Domestik","Sabang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Malikus Saleh","LSW","Domestik","Lhokseumawe");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Hamzah Fansuri","SKL","Domestik","Singkil");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Teuku Cut Ali","TPK","Domestik","Tapaktuan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kuala Namu","KNO","Internasional","Deli Serdang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Aek Godang","AEG","Domestik","Padang Lawas Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Binaka","GNS","Domestik","Gunung Sitoli");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Dr. F. L. Tobing / Pinangsori","SIX","Domestik","Tapanuli Tengah");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Lasondre","LSO","Domestik","Nias Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sibisa","SIW","Domestik","Toba Samosir");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Silangit","SQT","Domestik","Tapanuli Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Minangkabau International Airport","PDG","Internasional","Padang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Rokot","RKI","Domestik","Kep. Mentawai");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Syarif Kasim II","PKU","Internasional","Pekanbaru");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Japura,Rengat","RGT","Domestik","Indragiri Hulu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Pasir Pengaraian","PPR","Domestik","Rokan Hulu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Raja Haji Fisabilillah","TNJ","Internasional","Tanjungpinang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Hang Nadim","BTH","Internasional","Batam");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Dabo","SIG","Domestik TNI","Singkep,Lingga");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Raja Haji Abdullah","TJB","Domestik TNI","Karimun");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Mahmud Badaruddin II","PLM","Internasional","Palembang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Silampari","LLG","Domestik","Lubuklinggau");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Fatmawati Soekarno","BKS","Domestik","Kota Bengkulu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Muko-muko","MPC","Domestik","Muko-muko");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Depati Parbo","KRC","Domestik","Kerinci");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Muara Bungo","MRB","Domestik","Bungo");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Thaha","DJB","Domestik","Kota Jambi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Radin Inten II","TKG","Domestik","Lampung Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Depati Amir","PGK","Domestik","Pangkal Pinang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("H.A.S. Hanandjoeddin","TJQ","Domestik","Belitung");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Halim Perdana Kusuma","HLP","Internasional","Jakarta Timur");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Husein Sastranegara","BDO","Internasional","Bandung");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Cakrabhuwanan","CBN","Domestik","Cirebon");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Adi Sumarno","SOC","Internasional","Boyolali");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ahmad Yani","SRG","Internasional","Semarang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Dewadaru","KWB","Domestik","Jepara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tunggul Wulung","CXP","Domestik","Cilacap");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Adi Sutjipto","JOG","Internasional","Sleman");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Abdurrahman Saleh","MLG","Domestik","Malang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bawean – Harun Thohir","BWN","Domestik","Gresik");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Blimbingsari","BWX","Domestik","Banyuwangi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Juanda","SUB","Internasional","Sidoarjo");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Trunojoyo","SUP","Domestik","Sumenep");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Budiarto","BTO","Domestik","Tangerang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Soekarno Hatta","CKG","Internasional","Tangerang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ngurah Rai","DPS","Internasional","Denpasar");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Nangapinoh","NPO","Domestik","Melawi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Pangsuma","PSU","Domestik","Kapuas Hulu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Rahadi Oesman","KTG","Domestik","Ketapang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Supadio","PNK","Internasional","Kubu Raya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Susilo","SQG","Domestik","Sintang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bersujud / Batu Licin","BTW","Domestik","Tanah Bambu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Gusti Sjamsir Alam","KBU","Domestik","Kotabaru");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kota Bangun","TJG","Domestik","Tabalong");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Syamsudin Noor","BDJ","Internasional","Banjarbaru");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Beringin","MTW","Domestik","Barito Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("H. Asan","SMQ","Domestik","Kotawaringin Timur");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Iskandar","PKN","Domestik","Kotawaringin Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kuala Kurun","KLK","Domestik","Gunung Mas");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kuala Pembuang","KLP","Domestik","Seruyan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sanggu","BTK","Domestik","Barito Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tjilik Riwut","PKY","Domestik","Palangkaraya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Samba","TMB","Domestik","Katingan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Datah Dawai","DTD","Domestik","Kutai Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kalimarau","BEJ","Domestik","Berau");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kota Bangun","KOD","Domestik","Kutai Kertanegara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Melalan Melak","MLK","Domestik","Kutai Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Aji Muhammad Sulaiman Sepinggan","BPN","Internasional","Balikpapan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Juwata","TRX","Internasional","Tarakan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Nunukan","NNX","Domestik","Nunukan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Seluwung/Malinau","MLN","Domestik","Malinau");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tanjung Harapan","TJS","Domestik","Bulungan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Yuvai Semaring","LBW","Domestik","Nunukan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Melongguane","MNA","Domestik","Kep. Talaud");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Naha","NAH","Domestik","Kep. Sangihe");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sam Ratulangi","MDC","Internasional","Manado");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kasiguncu","PSJ","Domestik","Poso");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Beto Ambari","BUW","Domestik","Bau-bau");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Haluoleo","KDI","Domestik","Konawe Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Matahora","WNI","Domestik","Wakatobi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sangia Nibandera","PUM","Domestik","Kolaka");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sugimanuru Muna","RAQ","Domestik","Muna3");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mutiara Sis-Al Jufri","PLW","Domestik","Palu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Pogogul Buol","UDL","Domestik","Buol");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Bantilan","TLI","Domestik","Toli-toli");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Syukuran Aminuddin Amir","LUW","Domestik","Banggai");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Andi Jemma","MXB","Domestik","Luwu Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Arung Palakka / Bone","BXE","Domestik","Bone");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bua","LLO","Domestik","Luwu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("H. Aroeppala Selayar","SLY","Domestik","Selayar");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Pongtiku","TTR","Domestik","Tana Toraja");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Rampi","RPI","Domestik","Luwu Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Seko","SKO","Domestik","Luwu Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Hasanuddin","UPG","Internasional","Maros");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Djalaluddin","GTO","Domestik","Gorontalo");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sumarorong","MSA","Domestik","Mamasa");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tampa Padang","MJU","Domestik","Mamuju");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Lombok Praya","LOP","Internasional","Lombok Tengah");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Lunyuk","LYP","Domestik","Sumbawa");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Muhammad Kaharuddin","SWQ","Domestik","Sumbawa");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Muhammad Salahuddin","BMU","Domestik","Bima");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("A.A Bere Tallo / Atambua","ABU","Domestik","Belu");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("David Constantijn Saudale","RTI","Domestik","Rote Ndao");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("El Tari","KOE","Internasional","Kupang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Frans Sales Lega","RTG","Domestik","Manggarai");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Fransiskus Xaverius Seda","MOF","Domestik","Sikka");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Gewayantana","LKA","Domestik","Flores Timur");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("H. Hasan Aroeboesman","ENE","Domestik","Ende");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Labuhan Bajo – Komodo","LBJ","Domestik","Manggarai Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mali","ARD","Domestik","Alor");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("SOA","BJW","Domestik","Ngada");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tambolaka","TMC","Domestik","Sumba Barat Daya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tardamu","SAU","Domestik","Sabu Raijua");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Umbu Mehang Kunda","WGP","Domestik","Sumba Timur");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Wonopito","LWE","Domestik","Lembata");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Amahai","AHI","Domestik","Maluku Tengah");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bandaneira","NDA","Domestik","Maluku Tengah");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Dobo","DOB","Domestik","Kepulauan Aru");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("John Becker","KSX","Domestik","Maluku Barat Daya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mathilda Batlayeri","SXK","Domestik","Maluku Tenggara Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Namlea / Namniwel","NAM","Domestik","Buru");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Namrole","NRE","Domestik","Buru Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Pattimura","AMQ","Internasional","Ambon");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Wahai","WHI","Domestik","Maluku Tengah");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Buli","BLI","Domestik","Halmahera Timur");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Emalamo","SQN","Domestik","Kepulauan Sula");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Gamar Malamo","GLX","Domestik","Halmahera Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kuabang Kao","KAZ","Domestik","Halmahera Utara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Oesman Sadik","LAH","Domestik","Halmahera Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sultan Babullah","TTE","Domestik","Ternate");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Aboy","ABY","Domestik","Pengunungan Bintang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Batom","BXM","Domestik","Pengunungan Bintang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Beoga","BXD","Domestik","Puncak Jaya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bilorai","UGU","Domestik","Intan Jaya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bokondini","BUI","Domestik","Tolikara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bomakia","BXG","Domestik","Boven Digoel");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Dabra","DRH","Domestik","Mamberamo Raya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Elelim","ELR","Domestik","Yalmo");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Enarotali","EWI","Domestik","Paniai");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ewer","EWE","Domestik","Asmat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Frans Kaisiepo","BIK","Internasional","Biak Numfor");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ilaga","ILA","Domestik","Puncak");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kamur","KMR","Domestik","Asmat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Karubaga","KBF","Domestik","Tolikara");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kelila","LLN","Domestik","Pegunungan Bintang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kepi","KEI","Domestik","Mappi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kimaam","KMM","Domestik","Merauke");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kokonao","KOX","Domestik","Mimika");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Lereh","LHI","Domestik","Keerom");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mararena – Sarmi","ZRM","Domestik","Sami");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mindiptana","MDP","Domestik","Boven Digoel");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Moanamani","ONI","Domestik","Nabire");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mopah","MKQ","Internasional","Merauke");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mozes Kilangin Timika","TIM","Domestik","Mimika");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Mulia","LII","Domestik","Puncak Jaya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Nop Goliat Dekai Yahukimo","DEX","Domestik","Yahukimo");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Numfoor/Biak Numfoor","FOO","Domestik","Biak Numfor");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Okaba","OKQ","Domestik","Merauke");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Oksibil","OKL","Domestik TNI","Pengunungan Bintang");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Senggo","ZEG","Domestik","Mappi");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Sentani","DJJ","Domestik","Jayapura");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Stevanus Rumbewas Serui","ZRI","Domestik","Kep. Yapen");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tanah Merah","TMH","Domestik","Boven Digoel");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Tiom","TMY","Domestik","Lanny Jaya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ubrub","UBR","Domestik","Keerom");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Waghete","WET","Domestik","Deiyai");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Wamena","WMX","Domestik","Jayawijaya");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Waris Baru / Towe Hitam","WAR","Domestik","Keerom");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Yuruf","RUF","Domestik","Keerom");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Anggi","AGD","Domestik","Papua Barat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ayawasi","AYW","Domestik","Maybrat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Babo","BXB","Domestik","Teluk Bintuni");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Bintuni","NTI","Domestik","Teluk Bintuni");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Domine Eduard Osok","SOQ","Domestik","Sorong");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Inanwatan","INX","Domestik","Sorong Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kambuaya","KBX","Domestik","Maybrat");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Kebar","KEQ","Domestik","Tambrauw");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Merdey","RDE","Domestik","Teluk Bintuni");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Ransiki","RSK","Domestik","Manokwari");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Rendani","MKW","Domestik","Manokwari");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Teminabuan","TMX","Domestik","Sorong Selatan");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Torea","FKQ","Domestik","Fakfak");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Utarom","KNG","Domestik","Kaimana");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Wasior","WSR","Domestik","Teluk Wondama");
INSERT INTO `airport` (`name`,`code`,`category`,`location`) VALUES ("Werur","WRR","Domestik","Papua Barat");

-- FLIGHT --
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("7X2PDEZM","LAH","WNI",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 678 minute),594697,9);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("N8H6049H","ELR","LLO",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 562 minute),884228,169);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("969QD6JP","LII","RGT",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 656 minute),66293,139);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("KXALATR1","TPK","EWE",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 523 minute),288869,100);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("2A5YPXKQ","AEG","BTO",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 698 minute),105422,143);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("AAZGQF6T","RKI","DEX",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 647 minute),529038,88);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NW6FAP00","SAU","DRH",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 527 minute),501971,178);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("EP5H2XSM","CBN","GTO",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 682 minute),616736,35);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("UT2B9DV5","OKL","BMU",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 623 minute),32604,172);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("ZMZSBJA8","PPR","MKW",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 638 minute),744855,159);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("9V8OBDTD","INX","SBG",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 657 minute),826355,133);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("4EASN60J","PPR","LAH",DATE_ADD(NOW(), interval 480 minute),DATE_ADD(NOW(), interval 592 minute),643107,130);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1G5A5QMG","NPO","BTO",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2154 minute),396098,194);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("52WMNP87","MRB","KWB",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 1957 minute),955113,67);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("Y61IG87X","BTH","KEI",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2138 minute),990135,60);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("G9YJSKP2","WMX","WAR",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2102 minute),557906,39);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("LO8T3I99","RKI","BPN",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2129 minute),864998,90);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1FYQFO9G","MDP","ZRM",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2041 minute),1826,123);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NEYHBZJA","SUB","MLG",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2107 minute),920662,163);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("UPBI90DD","SKO","TJS",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2109 minute),234548,100);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("ELIEEHO4","KEQ","SOQ",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2092 minute),479022,189);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("7AFMCMDE","MLK","NRE",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2028 minute),549078,144);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("G49M1YH5","MEQ","SMQ",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 2102 minute),913420,82);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("RKJYRJSB","KMR","HLP",DATE_ADD(NOW(), interval 1920 minute),DATE_ADD(NOW(), interval 1989 minute),514573,62);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("KIC4VP1A","KMM","NAH",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3413 minute),103459,143);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("CNU002N4","LSW","TMH",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3580 minute),914446,151);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("R2KWP1VQ","LLG","TJQ",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3452 minute),474156,124);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("936S82C4","AHI","NTI",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3472 minute),301500,141);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1CE0F07M","SOC","MKQ",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3444 minute),331281,93);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("YPEL3F90","WSR","BDJ",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3429 minute),288287,118);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("KW7C6QD5","ZRM","KWB",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3418 minute),516298,189);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("GR6TAHW3","LBJ","BPN",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3522 minute),396879,24);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("FDTP1G77","UDL","LBJ",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3594 minute),580572,180);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("LH81PE9M","KBF","LLN",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3568 minute),511197,28);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("846IOB4J","SRG","BTO",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3540 minute),333380,73);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("CG65I0PL","MTW","PPR",DATE_ADD(NOW(), interval 3360 minute),DATE_ADD(NOW(), interval 3536 minute),945588,198);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("S93DUTJW","BEJ","TJB",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4927 minute),120101,82);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1AZPG89X","KRC","ABY",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4912 minute),655100,156);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("64B8A82W","TTE","RAQ",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4882 minute),544256,110);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("9QG612DM","GNS","KNO",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 5002 minute),236834,9);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("O4Y8QO9Y","BXG","AYW",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 5018 minute),174313,166);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("CZU8YT0J","RKI","RTG",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 5024 minute),907722,25);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("PZWQ8C3A","RKI","EWI",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4916 minute),762991,186);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("V94WSK2F","TLI","BLI",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4902 minute),115195,157);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("D4YPOHZ6","BXD","KAZ",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4962 minute),228196,80);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("ETAP7MJA","PLW","BTK",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4989 minute),33221,161);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("JRGPGLB4","MDP","ILA",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4833 minute),534570,130);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("EUUZDX4L","GTO","KWB",DATE_ADD(NOW(), interval 4800 minute),DATE_ADD(NOW(), interval 4978 minute),54731,193);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("GI224J69","PSU","KNG",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6271 minute),380503,144);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("QLOFKUJX","BTW","BXE",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6432 minute),423761,41);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("MHIG7WXI","LWE","ARD",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6452 minute),7153,2);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("MV5TB04U","KNG","PPR",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6409 minute),574091,8);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("3YCWME42","TMB","SUP",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6289 minute),785255,103);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("9R41IHIH","SKL","NAM",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6434 minute),258692,72);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("V8S0ORC5","BDO","WMX",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6422 minute),254133,2);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("IPHNKH5C","BXG","SIW",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6382 minute),328221,128);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("9T9ENZL3","ABY","BDO",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6464 minute),208844,79);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1YFL63BX","BXD","SLY",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6312 minute),482519,198);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("EGKZC27O","KLP","RGT",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6293 minute),593438,9);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("0H50NO5D","BTH","KLP",DATE_ADD(NOW(), interval 6240 minute),DATE_ADD(NOW(), interval 6330 minute),127211,39);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("4LZNC2L1","TTR","BIK",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7733 minute),901411,74);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("N8K9HAK7","SIW","MPC",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7744 minute),978370,171);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("8AIN1W04","ONI","SAU",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7811 minute),726913,95);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("UF8TQQPO","NDA","NAH",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7811 minute),562518,14);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("VE7C40RY","MRB","PGK",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7717 minute),611054,182);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("GR3NE752","KNO","MXB",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7909 minute),153784,158);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("OYYYUD05","KOD","BTK",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7919 minute),983636,9);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("0CZ61DEZ","MKQ","KBX",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7898 minute),750901,174);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("KOR4SMHE","KNG","SKL",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7881 minute),209834,58);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("ZYL1O4PZ","LYP","UDL",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7771 minute),900053,104);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("HN8NA881","MNA","BUW",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7754 minute),701084,61);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("2FGP4W3A","BLI","KRC",DATE_ADD(NOW(), interval 7680 minute),DATE_ADD(NOW(), interval 7746 minute),11102,103);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("336ZJA91","SOC","MDP",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9159 minute),913107,57);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("RU4A8JC9","WAR","KOX",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9280 minute),335972,60);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("N9VTFV6E","ZEG","BTW",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9223 minute),451067,11);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("5NIGVX97","BIK","KBU",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9269 minute),470781,49);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("STX854KY","FOO","MNA",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9234 minute),355773,151);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("C0UH42BS","PPR","SUB",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9317 minute),889127,75);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("T27MLGMC","ILA","TRX",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9167 minute),872686,148);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NLUP0HUD","LLG","KLP",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9307 minute),227975,130);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("WZL3F20T","MTW","SUB",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9251 minute),669607,47);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("PTKD1VAN","NAM","BXD",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9227 minute),668692,183);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("A9S1NHH8","BJW","UBR",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9260 minute),227031,158);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("BP19WKQ8","UPG","MLG",DATE_ADD(NOW(), interval 9120 minute),DATE_ADD(NOW(), interval 9255 minute),309833,193);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NH9IF6K7","NAM","BXD",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10677 minute),514780,134);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("C38XY5ZD","DRH","SNB",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10723 minute),832738,117);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NXTA9P6T","SIG","BWX",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10797 minute),957711,34);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("5Q8H7FHO","MDP","SLY",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10632 minute),378443,169);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("7O8TTQTD","SIG","WMX",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10649 minute),510431,35);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NOK6XNUX","DPS","BXD",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10694 minute),901561,116);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("A8FSNR9U","ZRI","WNI",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10726 minute),659766,14);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("5QKUZXYU","WRR","CBN",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10603 minute),816797,36);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("Q7N7EZ5O","KLK","RAQ",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10618 minute),82760,79);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("Q9LRNFQJ","SIG","MDP",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10681 minute),902424,185);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("J4HF8VFQ","LLG","WHI",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10661 minute),253008,40);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("J4XMHO2A","AGD","SIX",DATE_ADD(NOW(), interval 10560 minute),DATE_ADD(NOW(), interval 10651 minute),722517,35);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("I4ST71SP","DEX","AGD",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12100 minute),622207,113);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("JJHO8N92","TJG","KEQ",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12133 minute),642180,177);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("JROSACZR","TIM","BUI",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12124 minute),185249,154);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("NQ1L3N4T","BTO","BTJ",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12240 minute),504209,120);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("DWX7W1SL","PKN","CKG",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12098 minute),435315,181);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("KUKLVHWX","TMC","SQT",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12182 minute),692677,155);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("ZA93HLPD","PSU","SXK",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12124 minute),109109,9);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("IDLJBEM1","MJU","MRB",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12064 minute),955828,89);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("L1YOPER2","LOP","KTG",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12192 minute),604284,13);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("YIIB5ZPK","KMR","LWE",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12240 minute),674970,123);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("RQ0DBBRQ","LHI","KWB",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12040 minute),234104,189);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("0HEVAMD2","CKG","BXD",DATE_ADD(NOW(), interval 12000 minute),DATE_ADD(NOW(), interval 12112 minute),224919,75);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("1HEEP9BY","TRX","TJG",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13470 minute),668081,164);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("QSG1QXQ5","ONI","SKL",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13648 minute),297432,25);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("OAD3FTEW","KOE","AYW",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13611 minute),521755,118);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("PK3U4EV0","LWE","KTG",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13644 minute),183349,154);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("RHOI6MZU","RTI","BTH",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13675 minute),879022,161);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("86S9NV00","BLI","LII",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13667 minute),927619,125);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("3SOMZT8G","UDL","PKY",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13557 minute),122451,180);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("WUPTPR4R","LBW","LUW",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13676 minute),654619,25);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("0RDQMRWE","BXD","KWB",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13551 minute),879315,45);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("2BYPT6EO","MXB","BWX",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13610 minute),23589,144);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("XJ8OKCUZ","PKN","RSK",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13545 minute),507395,56);
INSERT INTO `flight` (`flight_id`,`origin_airport`, `destination_airport`, `departure_date`, `arrival_date`, `price`, `remaining_seat`) VALUES ("LEY24H0L","KLP","CKG",DATE_ADD(NOW(), interval 13440 minute),DATE_ADD(NOW(), interval 13530 minute),564758,34);
